#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "forgejo-runner"
name = "Forgejo Runner"
description.en = "Runner for Forgejo"
description.fr = "Runner pour Forgejo"

version = "8.0.1~ynh1"

maintainers = ["eric_G", "asandikci"]

[upstream]
license = "MIT"
admindoc = "https://forgejo.org/docs/next/admin/actions/#forgejo-runner"
code = "https://code.forgejo.org/forgejo/runner"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "615M"
ram.build = "250M"
ram.runtime = "50M"

[install]
    [install.token]
    ask.en = "This token can be retrieved at this location: https://forgejo.domain.tld/admin/actions/runners"
    ask.fr = "Ce token peut être récupéré à cet emplacement : https://forgejo.domain.tld/admin/actions/runners"
    type = "string"
    example = "xxxx"

    [install.forgejo_url]
    ask.en = "Please enter Forgejo instance URL"
    ask.fr = "Veuillez entrer l'URL de votre instance Forgejo"
    type = "string"
    example = "https://forge.domain.tld"

    [install.runner_name]
    ask.en = "The runner's name visible on the forge"
    ask.fr = "Le nom de l'exécuteur visible sur la forge"
    type = "string"
    example = "runner"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v8.0.1/forgejo-runner-8.0.1-linux-amd64"
        amd64.sha256 = "fc5473e11baa8f5ace72cd4369d84d8af2ce48fa9adca94c362a8288ecc46b93"
        arm64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v8.0.1/forgejo-runner-8.0.1-linux-arm64"
        arm64.sha256 = "2699653bb65ea6dd61d8c61c43ee811d4774199e56da08cea244b6b37e834d47"
        in_subdir = false
        extract = false
        rename = "forgejo-runner"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.apt]
    packages = "ca-certificates, git, curl, tar"

    extras.docker.repo = "https://download.docker.com/linux/debian bullseye stable"
    extras.docker.key = "https://download.docker.com/linux/debian/gpg"
    extras.docker.packages = "docker-ce, docker-ce-cli, containerd.io"
