#!/bin/bash

source /usr/share/yunohost/helpers

docker_image="alpine:latest"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/forgejo-runner"

#=================================================
# SETUP GROUPS
#=================================================
ynh_script_progression "Adding groups to user..."
#user needs access to yunohost ssl certs if no
usermod -a -G ssl-cert "$app"
#user need to access docker daemon
usermod -a -G docker "$app"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd

yunohost service add $app --description="Runner for Forgejo" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

pushd $install_dir
	./forgejo-runner create-runner-file --instance $forgejo_url --secret $token
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
