#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

forgejo_url=$YNH_APP_ARG_FORGEJO_URL
token=$YNH_APP_ARG_TOKEN
docker_image="alpine:latest"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/forgejo-runner"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd

yunohost service add $app --description="Runner for Forgejo" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

pushd $install_dir
	./forgejo-runner register --instance $forgejo_url --token $token --name $runner_name --no-interactive
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
