#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chmod +x "$install_dir/forgejo-runner"

#=================================================
# SETUP GROUPS
#=================================================
ynh_script_progression "Adding groups to user..."
#user needs access to yunohost ssl certs if no
usermod -a -G ssl-cert "$app"
#user need to access docker daemon
usermod -a -G docker "$app"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="Runner for Forgejo" --log="/var/log/$app/$app.log"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
